{% set name = "gitflow" %}
{% set version = "1.0.2" %}
{% set pipname = "nu-gitflow" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ pipname[0] }}/{{ pipname }}/nu-gitflow-{{ version }}.tar.gz
  sha256: bec2f5d99244e3e0b6587f0dc7fce87e26291724c704f3a771d57f3121c4e1e7

build:
  entry_points:
    - git-flow = gitflow.bin:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - ez_setup
    - pip
  run:
    - python >={{ python_min }}
    - gitpython >=1.0.1
    - future

test:
  imports:
    - gitflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/chassing/gitflow/
  summary: Git extensions to provide high-level repository operations for Vincent Driessen's branching model
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
